title: 8BitSoftware
url: "https://8bitsian.github.io/"
description: A website built with Markdown
theme: minima


header_pages:
- index.md
- about.md
- projects.md
- resume.md
- contact.md

exclude:
- README.md
